### ISSUE TITLE
test certs have expired (20 Jan 2018). Could those be refreshed?

### ISSUE THREAD

**Issue by pixelb** [cedadev/ndg_httpsclient#16]

**Comment by philipkershaw** [comment]
@pixelb, I've updated and pushed to devel.  Please give it a try.  If all OK I'll mint a new release

**Comment by pixelb** [comment]
Cool the updated certs worked.
Caveats, the commit added build/...  You may want to add build/ to .gitignore
Also localhost.crt doesn't contain the textual info at the top.
Anyway tests now pass.

thanks!

**Comment by philipkershaw** [comment]
Missed that - thanks.  Will cut a new release
