### ISSUE TITLE
maximum number of alt names

### ISSUE THREAD

**Issue by pegler** [cedadev/ndg_httpsclient#17]
There is a hardcoded limit of 64 alt names that is causing some problems for us. Specifically, https://files.pythonhosted.org points to Fastly, which uses a shared cert with more than 64 alt names. This is causing pip to be unable to install anything, which is an interesting catch-22 if the limit for this package does get increased. I'm curious why this limit exists because I don't believe there is a hard limit when creating certificates.

https://github.com/cedadev/ndg_httpsclient/blob/master/ndg/httpsclient/subj_alt_name.py#L28
https://github.com/cedadev/ndg_httpsclient/blob/master/ndg/httpsclient/subj_alt_name.py#L150

**Comment by pegler** [comment]
it looks like this addressed in urllib3 in version 1.8: https://github.com/urllib3/urllib3/blob/master/CHANGES.rst#18-2014-03-04

**Comment by philipkershaw** [comment]
I never thought that there would be a cert with > 64 subject alt names! :)   64 is just a convenient default from code I adapted for use with this package.  As you say, there doesn't seem to be a hard-limit - looking at https://www.ietf.org/rfc/rfc5280.txt   I don't think there'll be an easy way to dynamically allocate an arbitrary number of names in the code.  When I can get to a decent Internet connection I'll investigate.  Failing that I suggest bumping up the limit to 1024.  Hopefully no one will want a cert with that many.

**Comment by philipkershaw** [comment]
I've commited the fix in devel and tested it against https://files.pythonhosted.org.  I explicitly set it to match the wildcard *.pythonhosted.org.  Please give it a try.

I could make a change to the SAN verification to support wildcards explicitly or it may be better to leave control to the caller to explicitly set the hostname to match.

**Comment by philipkershaw** [comment]
Release on to PyPI as version 0.5.0

**Comment by pegler** [comment]
awesome, thanks @philipkershaw! I will check it out soon
