### ISSUE TITLE
LICENSE missing from pypi package

### ISSUE THREAD

**Issue by Sp1l** [cedadev/ndg_httpsclient#7]
The tarball from pypi misses the LICENSE file. Currently type of license can only be determined by visiting the GitHub project repo.

BSD License is specified yet there should at least be mention of the _type_ of BSD license (2-clause/simplified, 3-clause/New/Revised, 4-clause/Original/Old).

**Comment by philipkershaw** [comment]
I've moved into the package and updated `setup.py`.  It is in `devel` ready for a `0.4.1` release.

**Comment by Sp1l** [comment]
Thanks!
