### ISSUE TITLE
v0.4.1 was not pushed to PyPI

### ISSUE THREAD

**Issue by cclauss** [cedadev/ndg_httpsclient#8]
See: https://github.com/ubershmekel/python3wos/issues/22

Python 3 Wall of Superpowers http://python3wos.appspot.com/

**Comment by cclauss** [comment]
https://github.com/cedadev/ndg_httpsclient/blob/master/setup.py#L145 contains the line `'Programming Language :: Python :: 3'`, but https://pypi.python.org/pypi/ndg-httpsclient does not.

**Comment by philipkershaw** [comment]
Done now.  0.4.1 is on PyPI
